"""
Summarizer agent — runs ONCE at the very end of a successful pipeline.

Reads every approved implementation file from the output folder and writes
a human-readable README.md into that same folder explaining:
  - what the module does
  - every public function: signature, purpose, arguments, return value, exceptions
  - usage examples
  - how to run the tests
"""
from __future__ import annotations

import os
from google import genai
from dotenv import load_dotenv

load_dotenv()
_client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))

MODEL = "gemini-2.5-flash"

_SYSTEM = """\
You are a technical writer. You will be given one or more Python source files \
that were auto-generated by an AI coding pipeline, plus the original feature request \
that produced them. Write a clear, detailed README.md for this code.

The README must contain exactly these sections in this order:
1. # <Module name> — one-line description
2. ## What it does — 2-4 sentence plain-English summary
3. ## Public API — for every public function: signature, what it does, every \
argument with type and meaning, return value, every exception it raises and why
4. ## Usage examples — 3-5 concrete Python code examples showing typical and \
edge-case usage, formatted as ```python blocks
5. ## Running the tests — exact pytest command to run the test file
6. ## Acceptance criteria — bullet list of every criterion the code was tested against

Output only valid Markdown. No extra commentary outside the sections above."""


def summarize(
    feature_request: str,
    output_dir: str,
    approved_files: dict[str, str],
) -> str:
    """
    Generate a README.md in output_dir summarizing all approved_files.

    Args:
        feature_request: The original user prompt.
        output_dir:      Absolute path to the output/<run_id>/ folder.
        approved_files:  {file_path: content} of every approved implementation.

    Returns:
        The path to the written README file.
    """
    # Build the prompt — include every approved implementation file
    # (skip test files so the model focuses on the public API)
    impl_parts = []
    for path, content in approved_files.items():
        if not os.path.basename(path).startswith("test_"):
            impl_parts.append(f"### File: {os.path.basename(path)}\n```python\n{content}\n```")

    if not impl_parts:
        return ""

    user_prompt = "\n\n".join([
        f"Original feature request:\n{feature_request}",
        "Source files to document:",
        *impl_parts,
    ])

    response = _client.models.generate_content(
        model=MODEL,
        config={"system_instruction": _SYSTEM, "max_output_tokens": 2048},
        contents=user_prompt,
    )
    readme_text = response.text.strip()

    # Strip accidental outer markdown fences if the model wraps the whole thing
    if readme_text.startswith("```markdown"):
        readme_text = readme_text[len("```markdown"):].lstrip()
        if readme_text.endswith("```"):
            readme_text = readme_text[:-3].rstrip()

    readme_path = os.path.join(output_dir, "README.md")
    with open(readme_path, "w") as fh:
        fh.write(readme_text)

    return readme_path
